### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by adarsh-goel** [xorgram/xor#225] opened 2022-07-22 15:32 UTC
[0m[1m[31merror[0m: Uncaught (in promise) TypeError: Must be a file URL.
2022-07-22T15:31:35.877517+00:00 app[worker.1]:     throw new TypeError("Must be a file URL.");
2022-07-22T15:31:35.877518+00:00 app[worker.1]: [0m[31m          ^[0m
2022-07-22T15:31:35.877519+00:00 app[worker.1]:     at [0m[1m[3mfromFileUrl[0m ([0m[36mhttps://deno.land/std@0.149.0/path/posix.ts[0m:[0m[33m492[0m:[0m[33m11[0m)
2022-07-22T15:31:35.877523+00:00 app[worker.1]:     at [0m[36mhttps://raw.githubusercontent.com/xorgram/xor/0.1.0/main.ts[0m:[0m[33m21[0m:[0m[33m18[0m
2022-07-22T15:31:36.021112+00:00 heroku[worker.1]: Process exited with status 1
2022-07-22T15:31:36.164774+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by roj1512** [comment] 2022-07-22 15:33
Duplicate of #222.

**Closed by roj1512** 2022-07-22 15:33 UTC
